# action.yml
name: 'Sending Email'
description: 'Send notifications to a specified email.'
inputs:
  DESTINATION_EMAIL:  # id of input
    description: 'Destination for sending email to, should be repo/org admin'
    required: true
    default: 'example@gmail.com'
  GITHUB_RUNID:
    description: 'Run ID of the Github workflow job'
    required: true
  GITHUB_REPO:
    description: 'Repo name that runs Github workflow job'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
